"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Command as CommandIcon, Copy, Download, GitFork as Github, Menu, Pause, Play, Plus, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { profile, projects, traces, journey, githubSnapshot, type Project } from "@/data/portfolio";
import CapabilitySystem from "./CapabilitySystem";
import { SignalField, TaylorPlot, RepoFlow, MeetingDiagram, CompilerDiagram } from "./Visuals";

const External=({href,children,className=""}:{href:string;children:React.ReactNode;className?:string})=><a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>;
const SectionLabel=({number,children}:{number:string;children:React.ReactNode})=><div className="section-label mono"><span>{number}</span><span>{children}</span></div>;
const Tags=({items}:{items:string[]})=><div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div>;

function ProjectCopy({project,onOpen}:{project:Project;onOpen:(p:Project)=>void}){
 return <div className="project-copy"><span className="mono project-category">{project.number} / {project.category}</span><h3>{project.name}</h3><p className="project-headline">{project.headline}</p><p className="project-description">{project.description}</p><Tags items={project.stack}/><div className="project-actions"><button onClick={()=>onOpen(project)} className="text-button" data-cursor="READ">Inside the project <ArrowUpRight size={18}/></button><External href={project.repository} className="source-link" ><Github size={18}/><span className="sr-only">{project.name} source on GitHub</span></External></div><span className="project-role mono">{project.role}</span></div>;
}

function EvidenceGraph({onOpen}:{onOpen:(p:Project)=>void}){
 const [active,setActive]=useState(0);const trace=traces[active];
 return <div className="evidence-system reveal"><div className="evidence-top mono"><span>INPUT / SELECT A CAPABILITY</span><span>TRACE / FIND THE EVIDENCE</span></div><div className="evidence-grid"><div className="trace-inputs">{traces.map((t,i)=><button key={t.name} className={'trace-button '+(active===i?'active':'')} onClick={()=>setActive(i)} aria-pressed={active===i}><span><small className="mono">{t.domain}</small>{t.name}</span><span className="trace-port"/></button>)}</div><div className="trace-wires" aria-hidden="true"><svg viewBox="0 0 360 400" preserveAspectRatio="none">{traces.map((_,i)=><path key={'in'+i} className={i===active?'active-wire':'inactive-wire'} d={`M0 ${40+i*80} C120 ${40+i*80} 100 200 180 200`}/>)}{projects.map((p,i)=><path key={p.id} className={trace.projects.includes(p.id)?'active-wire':'inactive-wire'} d={`M180 200 C260 200 230 ${40+i*80} 360 ${40+i*80}`}/>)}<circle className="wire-core" cx="180" cy="200" r="9"/></svg><div className="trace-count mono">0{trace.projects.length}<span>CONNECTIONS</span></div></div><div className="trace-outputs">{projects.map(p=><button key={p.id} className={'trace-project '+(trace.projects.includes(p.id)?'linked':'')} onClick={()=>onOpen(p)} aria-label={`Read ${p.name} case study${trace.projects.includes(p.id)?`, uses ${trace.name}`:''}`}><span className="trace-port"/><span><small className="mono">PROJECT {p.number}</small>{p.name}</span><ArrowUpRight size={18}/></button>)}</div></div><div className="trace-description" aria-live="polite"><span className="mono">{trace.name} /</span><p>{trace.description}</p><small>{trace.detail}</small></div></div>;
}

export function GithubActivity(){
 const [data,setData]=useState(githubSnapshot);const [loading,setLoading]=useState(false);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const c=new AbortController();const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();setLoading(true);fetch('/api/github',{signal:c.signal}).then(r=>r.ok?r.json():Promise.reject()).then((payload:unknown)=>{const d=payload as typeof githubSnapshot;if(typeof d.publicRepos==='number'&&Array.isArray(d.events))setData(d);}).catch(()=>{}).finally(()=>setLoading(false));},{rootMargin:'250px'});if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();c.abort();};},[]);
 return <div className="github-panel reveal" ref={ref}><div className="github-heading"><Github size={27}/><span className="mono">@safiullah-24</span><span className="github-data-status mono">{loading?'UPDATING…':data.source==='live'?'LIVE PUBLIC DATA':'SNAPSHOT / 26 SEP 2026'}</span></div><div className="github-body"><div className="github-count"><span>{data.publicRepos}</span><p>public repositories</p><small>Including collaborative forks.</small></div><div className="activity-list">{data.events.length?data.events.slice(0,3).map((e,i)=><External key={e.repo+e.date+i} href={e.url} className="activity-row"><span className="activity-date mono">{new Date(e.date).toLocaleDateString('en-GB',{day:'2-digit',month:'short',timeZone:'UTC'}).toUpperCase()}</span><span><strong>{e.repo}</strong><small>{e.type}</small></span><ArrowUpRight size={17}/></External>):<p>No recent public events. The repositories still tell the story.</p>}</div></div><div className="github-bottom"><p>Work is a conversation. Pull requests are part of mine.</p><External href={profile.github} className="text-button">Explore GitHub <ArrowUpRight size={17}/></External></div></div>;
}

export function CaseStudy({project,onClose}:{project:Project|null;onClose:()=>void}){
 return <Dialog open={!!project} onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="case-dialog">{project&&<><span className="mono project-category">CASE STUDY / {project.number}</span><DialogTitle className="case-title">{project.name}</DialogTitle><DialogDescription className="case-subtitle">{project.headline}</DialogDescription><div className="case-status mono">{project.status}</div><Tags items={project.stack}/><div className="case-sections">{[['The problem',project.problem],['The system',project.approach],['My contribution',project.contribution],['Where it stands',project.outcome]].map(([title,text],i)=><section key={title}><span className="mono">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></section>)}</div><div className="case-links"><External className="button-primary" href={project.repository}>View repository <ArrowUpRight size={17}/></External><External className="text-button" href={project.evidence}>{project.evidenceLabel}<ArrowUpRight size={16}/></External></div></>}</DialogContent></Dialog>;
}

export default function Portfolio(){
 const [boot,setBoot]=useState(true);const [motion,setMotion]=useState(true);const [menu,setMenu]=useState(false);const [command,setCommand]=useState(false);const [selected,setSelected]=useState<Project|null>(null);const [copied,setCopied]=useState(false);const [toast,setToast]=useState('');const [chapter,setChapter]=useState('home');const cursor=useRef<HTMLDivElement>(null);
 const copyEmail=useCallback(async()=>{try{await navigator.clipboard.writeText(profile.email);setCopied(true);setToast('Email address copied.');setTimeout(()=>setCopied(false),2200);}catch{setToast(profile.email);}},[]);
 useEffect(()=>{const preference=window.matchMedia('(prefers-reduced-motion: reduce)');let stored:string|null=null;try{stored=localStorage.getItem('safi-motion');}catch{}const allowMotion=stored?stored==='full':!preference.matches;setMotion(allowMotion);const t=setTimeout(()=>setBoot(false),allowMotion?1200:0);const change=(e:MediaQueryListEvent)=>setMotion(!e.matches);preference.addEventListener('change',change);console.info('CodeWithSafi // Curiosity, compiled. Built to be explored. Press ⌘K or Ctrl+K to follow a thread.');return()=>{clearTimeout(t);preference.removeEventListener('change',change);};},[]);
 useEffect(()=>{document.documentElement.dataset.motion=motion?'full':'reduced';},[motion]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target);}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));const chapters=Array.from(document.querySelectorAll<HTMLElement>('main>section[id]'));let frame=0;const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{const progress=window.scrollY/Math.max(1,document.documentElement.scrollHeight-window.innerHeight);document.documentElement.style.setProperty('--scroll-progress',`${progress}`);const current=[...chapters].reverse().find(section=>section.getBoundingClientRect().top<=window.innerHeight*.3);setChapter(current?.id||'home');frame=0;});};window.addEventListener('scroll',scroll,{passive:true});scroll();return()=>{io.disconnect();window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};},[]);
 useEffect(()=>{let sequence='';const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(o=>!o);}if(e.key==='Escape')setMenu(false);if((e.target as HTMLElement).tagName==='INPUT')return;sequence=(sequence+e.key).slice(-10);if(sequence.endsWith('curiosity'))setToast('The best feature is the next question. Keep building. — Safi');};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(!motion||!matchMedia('(pointer:fine)').matches)return;const el=cursor.current;if(!el)return;let frame=0;const move=(e:PointerEvent)=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{el.style.transform=`translate3d(${e.clientX+18}px,${e.clientY+18}px,0)`;const target=(e.target as HTMLElement).closest('[data-cursor]');el.dataset.active=target?'true':'false';el.textContent=target?.getAttribute('data-cursor')||'OPEN';});};window.addEventListener('pointermove',move,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('pointermove',move);};},[motion]);
 const navigate=(id:string)=>{setCommand(false);setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:motion?'smooth':'instant'});};
 const toggleMotion=()=>{const next=!motion;setMotion(next);try{localStorage.setItem('safi-motion',next?'full':'reduced');}catch{}};
 return <>
  <a className="skip-link" href="#main">Skip to content</a>
  {boot&&<div className="boot-screen" aria-hidden="true"><img className="boot-logo" src="/brand/codewithsafi-lockup.webp" alt="" width="640" height="663"/><div className="boot-line"/><span className="mono">CODEWITHSAFI / CONNECTING IDEAS</span></div>}
  <div className="scroll-progress" aria-hidden="true"/>
  <div className="context-cursor mono" ref={cursor} aria-hidden="true"/>
  <header className="site-header"><a className="brand" href="#home" aria-label="CodeWithSafi — Safi Ullah home"><img className="brand-icon" src="/brand/codewithsafi-mark.webp" width="40" height="40" alt=""/><span className="brand-name">CodeWithSafi</span></a><nav className="desktop-nav" aria-label="Main navigation">{[['work','Work'],['graph','Stack'],['building','Poly'],['journey','Journey']].map(([id,label])=><a href={'#'+id} key={id} className={chapter===id?'current':''} aria-current={chapter===id?'location':undefined}>{label}</a>)}</nav><div className="header-actions"><button className="command-trigger" aria-label="Open command palette" onClick={()=>setCommand(true)}><CommandIcon size={14}/><span>K</span></button><a className="header-contact" href="#contact">Let’s talk <ArrowUpRight size={16}/></a><button className="mobile-menu" aria-expanded={menu} aria-controls="mobile-navigation" aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div></header>
  {menu&&<nav id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation">{[['home','Home'],['graph','Engineering stack'],['building','PolyBridge / Poly'],['work','Selected work'],['journey','My journey'],['contact','Let’s talk']].map(([id,label],i)=><a key={id} href={'#'+id} aria-current={chapter===id?'location':undefined} onClick={()=>setMenu(false)}><span className="mono">0{i}</span>{label}<ArrowUpRight/></a>)}</nav>}
  <main id="main">
   <section id="home" className={"hero section-shell "+(!boot?"hero-ready":"")} onPointerLeave={e=>{e.currentTarget.style.setProperty("--pointer-x","0px");e.currentTarget.style.setProperty("--pointer-y","0px");}} onPointerMove={e=>{if(!motion||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--pointer-x',`${((e.clientX-r.left)/r.width-.5)*9}px`);e.currentTarget.style.setProperty('--pointer-y',`${((e.clientY-r.top)/r.height-.5)*7}px`);}}>
    <div className="hero-topline mono"><span>INDEPENDENT MIND. INTERCONNECTED WORK.</span><span>LAHORE, PK <span className="coordinate">31.52° N / 74.35° E</span></span></div>
    <div className="hero-main"><div className="hero-copy"><div className="hero-intro"><span className="signal-square"/><span>Software engineer. Computer science student.</span></div><h1><span className="word-mask"><span>Curiosity,</span></span><span className="word-mask accent"><span>compiled.</span></span></h1><p className="hero-statement">I build systems, explore the unfamiliar,<br className="desktop-break"/> and turn difficult ideas into working software.</p><div className="hero-ctas"><a href="#work" className="button-primary">Explore my work <ArrowDown size={18}/></a><a href="#graph" className="hero-secondary">Explore the stack <Plus size={16}/></a></div><a className="hero-poly" href="#building"><span className="hero-poly-signal" aria-hidden="true"/><span><small className="mono">CREATOR / IN ACTIVE DEVELOPMENT</small><strong>PolyBridge <span>+</span> Poly</strong><em>A language interoperability system.</em></span><ArrowUpRight size={20}/></a></div><div className="hero-visual"><SignalField motion={motion&&!boot}/><div className="hero-signal-rails" aria-hidden="true"><span/><span/><i/><i/></div><div className="portrait-frame"><img src="/safi-portrait.webp" alt="Safi Ullah, software engineer and computer science student" width="1194" height="1317" fetchPriority="high"/><div className="portrait-shade"/><div className="portrait-scan" aria-hidden="true"/><span className="portrait-corner top-left"/><span className="portrait-corner bottom-right"/><div className="portrait-caption"><span>SAFI ULLAH</span><small className="mono">ENGINEER IN CONTINUOUS EVOLUTION</small></div></div><div className="portrait-index mono">[ HUMAN IN THE SYSTEM ]</div></div></div>
    <div className="hero-bottom"><div className="hero-disciplines mono"><span>AI</span><i>×</i><span>SYSTEMS</span><i>×</i><span>WEB</span></div><p>Always learning.<br/>Always building.</p><a href="#about" className="scroll-cue mono">SCROLL TO EXPLORE <ArrowDown size={17}/></a></div>
   </section>
   <section id="about" className="intro-section section-shell"><SectionLabel number="01">THE MINDSET</SectionLabel><div className="intro-content reveal"><h2>Good software starts<br/>with a better <em>question.</em></h2><div className="intro-prose"><p>I’m Safi Ullah, a software engineer and computer science student based in Lahore. I like the space where theory becomes something you can use.</p><p>That takes me from visualizing mathematics to connecting real-time systems, experimenting with AI, and asking how programming languages could work together.</p><a href="/resume" className="text-button">The résumé version <ArrowUpRight size={17}/></a></div></div><div className="principles reveal"><div><span className="mono">01 /</span><h3>Understand the problem.</h3><p>Get close to the constraints before getting attached to a solution.</p></div><div><span className="mono">02 /</span><h3>Make the idea work.</h3><p>Build, test, and make the technical decisions visible.</p></div><div><span className="mono">03 /</span><h3>Keep the question open.</h3><p>Every project should leave me with a better way to think.</p></div></div></section>
   <section id="graph" className="graph-section section-shell"><SectionLabel number="02">TECHNICAL PRACTICE</SectionLabel><div className="heading-row reveal"><h2>Every skill<br/>leaves a <em>trace.</em></h2><p>Languages, tools, and the thinking between them.<br/>Explore what I use—and what I’m learning next.</p></div><CapabilitySystem onOpen={setSelected}/><div className="graph-proof-heading reveal"><span className="mono">THE CONNECTION ENGINE</span><p>Now follow the skills into the work.</p></div><EvidenceGraph onOpen={setSelected}/></section>
   <section id="building" className="building-section section-shell"><SectionLabel number="03">ORIGINAL R&D / IN ACTIVE DEVELOPMENT</SectionLabel><div className="research-layout"><div className="research-copy reveal"><span className="research-badge mono">CREATOR OF POLYBRIDGE + POLY</span><h2>Many languages.<br/>One <em>conversation.</em></h2><p className="research-lead">My next question is a language of its own.</p><p>I conceived <strong>PolyBridge</strong> and the <strong>Poly</strong> language direction. I’m now developing the architecture and prototypes with my team.</p><p>Poly is the custom source format at the center of that vision: a place for Python, JavaScript, and C/C++ blocks to coexist, expose functions, and work together. PolyBridge is the broader system that aims to connect them.</p><p className="research-status"><span className="mono">CURRENT STAGE / ARCHITECTURE & PROTOTYPING</span>The syntax and execution model are still being designed. Type mapping, shared contracts, isolation, and cross-language overhead are questions we are actively working through.</p><div className="research-threads"><span>Static analysis</span><span>Sandboxing / isolation</span><span>AI-assisted translation</span><span>IDE integration</span><span>Extensible language adapters</span></div><a className="text-button" href={'mailto:'+profile.email+'?subject=Let%E2%80%99s%20talk%20about%20PolyBridge'}>Discuss PolyBridge <ArrowUpRight size={17}/></a></div><div className="reveal"><CompilerDiagram/></div></div><div className="poly-principles reveal"><div><span className="mono">01 / THE LANGUAGE</span><h3>Poly</h3><p>A proposed source format for expressing mixed-language blocks and the links between them.</p></div><div><span className="mono">02 / THE SYSTEM</span><h3>PolyBridge</h3><p>Adapters, shared contracts, and an execution layer designed to make those links explicit.</p></div><div><span className="mono">03 / THE RESEARCH</span><h3>Prove the boundary.</h3><p>Start with a small, testable prototype. Validate correctness, isolation, and overhead before expanding.</p></div></div></section>
   <section id="work" className="work-section section-shell"><div className="section-heading"><SectionLabel number="04">SELECTED WORK</SectionLabel><div className="heading-row reveal"><h2>Ideas with<br/><em>implementation.</em></h2><p>Different problems. A common thread:<br/>understand the system, then build it.</p></div></div><article className="project project-calculus reveal"><ProjectCopy project={projects[0]} onOpen={setSelected}/><div className="project-visual"><TaylorPlot/></div></article><article className="project project-repomind reveal"><div className="project-visual"><RepoFlow/></div><ProjectCopy project={projects[1]} onOpen={setSelected}/></article><article className="project project-meetforge reveal"><ProjectCopy project={projects[2]} onOpen={setSelected}/><div className="project-visual"><MeetingDiagram/></div></article><div className="project-notes reveal"><div className="notes-label mono">ALSO IN THE WORKBENCH</div>{projects.slice(3).map(p=><button className="project-note" key={p.id} onClick={()=>setSelected(p)} data-cursor="READ"><span className="mono note-number">{p.number}</span><span><strong>{p.name}</strong><small>{p.description}</small></span><span className="mono note-kind">{p.category}</span><ArrowUpRight size={25}/></button>)}</div></section>
   <section id="experience" className="experience-section section-shell"><SectionLabel number="05">BUILDING WITH OTHERS</SectionLabel><div className="experience-layout"><h2 className="reveal">Software is<br/>a team <em>sport.</em></h2><div className="experience-list"><div className="experience-row reveal"><span className="mono experience-year">2026</span><div><h3>QuantumLogicsLabs</h3><span className="experience-title">Web engineering intern · Open-source collaborator</span><p>Interactive calculus tools, repository intelligence, and collaboration across frontend and backend work. Contributed code, reviewed changes, and took on team-captain responsibilities.</p><External href="https://github.com/QuantumLogicsLabs/CalculusRuntime-Frontend/commits/main/?author=safiullah-24" className="text-button">See contributions <ArrowUpRight size={16}/></External></div></div><div className="experience-row reveal"><span className="mono experience-year">2026</span><div><h3>FlyRank</h3><span className="experience-title">Machine learning internship</span><p>Exploring search-intelligence data through notebooks, research questions, task framing, and data contracts. Learning to support each modeling decision with evidence.</p><External href={projects[3].repository} className="text-button">Open the lab <ArrowUpRight size={16}/></External></div></div><div className="experience-row reveal"><span className="mono experience-year">ONGOING</span><div><h3>Independent & client work</h3><span className="experience-title">Web development · Product thinking</span><p>Building full-stack projects and working on storefront experiences, product pages, and responsive interfaces. Connecting implementation decisions to how people actually use a product.</p></div></div></div></div></section>
   <section id="journey" className="journey-section section-shell"><SectionLabel number="06">AN EXPANDING PRACTICE</SectionLabel><div className="heading-row reveal"><h2>Built in layers.<br/><em>Still unfolding.</em></h2><p>The next thing I learn changes<br/>how I understand the last.</p></div><Tabs defaultValue="Foundations" className="journey-tabs reveal"><TabsList className="journey-list" aria-label="Explore Safi’s engineering journey">{journey.map((j,i)=><TabsTrigger key={j.name} value={j.name}><span className="mono">0{i+1}</span>{j.name}</TabsTrigger>)}</TabsList>{journey.map((j,i)=><TabsContent key={j.name} value={j.name} className="journey-content"><div className="journey-index" aria-hidden="true">0{i+1}</div><div><span className="mono">{j.label}</span><h3>{j.word}</h3><p>{j.text}</p><Tags items={j.tags}/></div></TabsContent>)}</Tabs></section>
   <section id="open-source" className="open-source-section section-shell"><SectionLabel number="07">OUT IN THE OPEN</SectionLabel><div className="heading-row reveal"><h2>The work continues<br/><em>between commits.</em></h2><p>Small iterations. Shared context.<br/>A public record of learning by building.</p></div><GithubActivity/></section>
   <section id="beyond" className="beyond-section section-shell reveal"><span className="mono">BEYOND THE REPOSITORY</span><p>Explaining technology through <strong>CodeWithSafi.</strong><br/>Finding patterns in unfamiliar systems.<br/>And learning that consistency matters—in code and in the gym.</p><span className="beyond-note mono">CURIOUS BY DEFAULT.</span></section>
   <section id="contact" className="contact-section section-shell"><SectionLabel number="08">THE NEXT CONNECTION</SectionLabel><div className="contact-main reveal"><p className="contact-kicker">HAVE A QUESTION WORTH BUILDING AROUND?</p><h2>Let’s make<br/>something <em>matter.</em></h2><a className="contact-email" href={'mailto:'+profile.email}>{profile.email}<ArrowUpRight/></a><div className="contact-options"><button onClick={copyEmail} className="text-button">{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy email'}</button><span>Projects, internships, research, or a good conversation.</span></div></div><div className="contact-links"><External href={profile.github}>GitHub <ArrowUpRight size={18}/></External><External href={profile.linkedin}>LinkedIn <ArrowUpRight size={18}/></External><a href="/resume">Résumé <ArrowUpRight size={18}/></a><External href={profile.leetcode}>LeetCode <ArrowUpRight size={18}/></External></div><footer><a className="footer-brand" href="#home" aria-label="CodeWithSafi home"><img src="/brand/codewithsafi-lockup.webp" alt="CodeWithSafi" width="640" height="663" loading="lazy"/></a><span className="mono">© 2026 SAFI ULLAH<br/>LAHORE, PAKISTAN</span><button className="motion-toggle mono" aria-pressed={!motion} onClick={toggleMotion}>{motion?<Pause size={14}/>:<Play size={14}/>} MOTION {motion?'ON':'REDUCED'}</button><a className="back-top mono" href="#home">BACK TO TOP <ArrowUpRight size={15}/></a></footer></section>
  </main>
  <CaseStudy project={selected} onClose={()=>setSelected(null)}/>
  <CommandDialog open={command} onOpenChange={setCommand} title="CodeWithSafi / Find your next connection" description="Search sections, projects, and contact actions." className="portfolio-command"><div className="command-brand"><img src="/brand/codewithsafi-mark.webp" alt="" width="26" height="26"/><span>CodeWithSafi</span><small className="mono">FOLLOW A THREAD</small></div><CommandInput placeholder="Where would you like to go?"/><CommandList><CommandEmpty>No matching connection. Try “projects” or “email”.</CommandEmpty><CommandGroup heading="CODEWITHSAFI / EXPLORE">{[['about','About Safi'],['work','Selected work'],['graph','Engineering stack / skills'],['experience','Experience'],['journey','My journey'],['building','PolyBridge + Poly / original R&D'],['open-source','GitHub activity'],['contact','Contact']].map(([id,label])=><CommandItem key={id} onSelect={()=>navigate(id)}>{label}<CommandShortcut>↗</CommandShortcut></CommandItem>)}</CommandGroup><CommandGroup heading="QUICK ACTIONS"><CommandItem onSelect={()=>{copyEmail();setCommand(false);}}><Copy/>Copy email</CommandItem><CommandItem onSelect={()=>{window.location.href='/resume';}}><Download/>View résumé</CommandItem><CommandItem onSelect={()=>{window.open(profile.github,'_blank','noopener,noreferrer');setCommand(false);}}><Github/>Open GitHub</CommandItem><CommandItem onSelect={()=>{toggleMotion();setCommand(false);}}>{motion?<Pause/>:<Play/>}{motion?'Reduce motion':'Enable motion'}</CommandItem></CommandGroup></CommandList><div className="command-footer mono"><span>↑ ↓ NAVIGATE</span><span>↵ OPEN</span><span>ESC CLOSE</span></div></CommandDialog>
  <div className={'toast mono '+(toast?'show':'')} role="status" aria-live="polite">{toast}</div>
 </>;
}
