"use client";
import {useState} from 'react';
import {ArrowUpRight, ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {capabilityGroups,projects,type Project} from '@/data/portfolio';

export function Orbit({className=''}:{className?:string}){
 return <svg className={'v4-orbit '+className} viewBox="0 0 700 700" fill="none" aria-hidden="true"><g className="v4-orbit-turn">{Array.from({length:13},(_,i)=><ellipse key={i} cx="350" cy="350" rx={84+i*17} ry="288" transform={`rotate(${i*13.8} 350 350)`}/>)}<circle cx="350" cy="350" r="290"/><path d="M30 350H670M350 30V670"/><circle className="orbit-node" cx="640" cy="350" r="4"/><circle className="orbit-node blue-node" cx="350" cy="60" r="3"/></g><circle cx="350" cy="350" r="3" className="orbit-node"/></svg>;
}
const groupNames=['Programming','Frontend','Backend','Data','AI / ML','Engineering','Exploring'];
export function Capabilities({onOpen}:{onOpen:(p:Project)=>void}){
 const [group,setGroup]=useState('core');const [index,setIndex]=useState(0);
 const activeGroup=capabilityGroups.find(g=>g.id===group)!;const selected=activeGroup.skills[Math.min(index,activeGroup.skills.length-1)];
 return <Tabs className="v4-atlas v4-reveal" value={group} onValueChange={g=>{setGroup(g);setIndex(0);}}>
  <div className="atlas-top v4-meta"><span>CAPABILITY ATLAS</span><span>SELECT A DISCIPLINE. FOLLOW THE EVIDENCE.</span></div>
  <div className="atlas-layout"><TabsList className="atlas-groups" aria-label="Engineering disciplines">{capabilityGroups.map((g,i)=><TabsTrigger value={g.id} key={g.id}><span className="v4-meta">0{i+1}</span><span>{groupNames[i]}</span><ArrowRight size={17}/></TabsTrigger>)}</TabsList>
  <div className="atlas-skills">{capabilityGroups.map(g=><TabsContent value={g.id} key={g.id}><span className="v4-meta atlas-instruction">PRACTICE / {g.label.toUpperCase()}</span>{g.skills.map((s,i)=><button key={s.name} onClick={()=>setIndex(i)} aria-pressed={index===i}><span>{s.name}</span><small>{s.status}</small></button>)}</TabsContent>)}</div>
  <div className="atlas-detail" aria-live="polite"><div className="atlas-detail-content" key={selected.name}><span className="v4-meta"><i/>{selected.status.toUpperCase()}</span><h3>{selected.name}</h3><p>{selected.description}</p><div className="atlas-link-line" aria-hidden="true"><span/><i/><span/></div><span className="v4-meta">{selected.projects.length?'FOLLOW INTO THE WORK':'CURRENT CONTEXT'}</span><div className="atlas-evidence">{selected.projects.map(id=>{const p=projects.find(p=>p.id===id)!;return <button key={id} onClick={()=>onOpen(p)}><span>{p.name}</span><ArrowUpRight size={19}/></button>;})}{!selected.projects.length&&<p>{selected.context}</p>}</div></div><span className="atlas-note">Practice, foundations, and exploration.<br/>{" "}No scores. Just context.</span></div>
  </div>
 </Tabs>;
}
export const polyStages=[
 {title:'Source',label:'01 / THE SOURCE FORMAT',heading:'Different languages. Explicit boundaries.',text:'Poly is the custom source-format direction I conceived for mixed-language blocks. Python, JavaScript, and C/C++ could share a source while keeping their own semantics.',code:['poly source / conceptual','python     normalize(data)','javascript render(result)','cpp        transform(input)'],meta:'PROPOSED FORMAT · SYNTAX UNDER DESIGN'},
 {title:'Adapters',label:'02 / LANGUAGE ADAPTERS',heading:'Preserve the language. Expose the contract.',text:'Adapters would parse or delegate each language block and expose its functions. A common adapter boundary keeps future language support extensible.',code:['adapter interface / proposed','parse        → language block','discover     → exported symbols','describe     → callable contract'],meta:'PYTHON / JAVASCRIPT / C / C++'},
 {title:'Contracts',label:'03 / SHARED UNDERSTANDING',heading:'Make every connection inspectable.',text:'A shared intermediate representation could record symbols, signatures, dependencies, and type mappings. Static analysis would check the boundaries before execution.',code:['shared representation / proposed','symbol       normalize','signature    data → result','type map     explicit conversion'],meta:'SYMBOLS / TYPE MAPPING / IR / STATIC ANALYSIS'},
 {title:'Calls',label:'04 / CROSS-LANGUAGE INVOCATION',heading:'A function call across a boundary.',text:'The research asks how arguments, return values, and errors can move between language environments predictably. Marshalling and call overhead need to be measured.',code:['call trace / illustrative','cpp::transform(input)','   → py::normalize(data)','      → js::render(result)'],meta:'EXPLICIT INPUTS / RESULTS / ERROR PROPAGATION'},
 {title:'Execution',label:'05 / COORDINATED EXECUTION',heading:'Prove the smallest useful system.',text:'Coordinate linked work, isolate execution, and collect the output. Correctness, resource limits, and overhead come before expanding into translation or IDE tooling.',code:['prototype priorities','01   correctness & isolation','02   measurable call overhead','03   developer feedback'],meta:'ARCHITECTURE & PROTOTYPING / NOT A RELEASED COMPILER'},
];
export function PolyInstrument(){
 const [stage,setStage]=useState(0);const s=polyStages[stage];
 return <div className="v4-poly-instrument" data-stage={stage}><div className="poly-instrument-bar v4-meta"><span>POLYBRIDGE / RESEARCH INSTRUMENT</span><span>PROPOSED ARCHITECTURE</span></div><div className="poly-machine">
 <div className="poly-source"><div className="poly-source-title"><span className="v4-meta">POLY / MIXED-LANGUAGE SOURCE</span><span className="source-bracket">{'{ }'}</span></div>{['Python','JavaScript','C / C++'].map((l,i)=><div className="poly-language" key={l}><span className="v4-meta">0{i+1}</span><span>{l}</span><span className="language-port"/></div>)}<p>Many language environments.<br/>{" "}One explicit source direction.</p></div>
 <div className="poly-core-visual" aria-hidden="true"><svg viewBox="0 0 400 300" preserveAspectRatio="none"><path d="M0 60 C80 60 60 150 125 150M0 150H125M0 240C80 240 60 150 125 150M275 150H400"/><path className="poly-flow-path" d="M0 150H400"/></svg><div className="poly-stack"><span>SYMBOLS</span><span>TYPE MAP</span><span>IR</span><strong>Poly<span>Bridge</span></strong></div><span className="v4-meta core-caption">{stage<2?'ADAPTER BOUNDARY':stage===2?'SHARED CONTRACTS':stage===3?'CALL RESOLUTION':'EXECUTION BOUNDARY'}</span></div>
 <div className="poly-readout" aria-live="polite"><span className="v4-meta">{s.label}</span><div key={stage} className="poly-code">{s.code.map((line,i)=><div key={line}><span>{String(i+1).padStart(2,'0')}</span><code>{line}</code></div>)}</div><span className="v4-meta poly-code-note">{s.meta}</span></div>
 </div><Tabs value={String(stage)} onValueChange={v=>setStage(Number(v))} className="poly-stage-control"><TabsList aria-label="Explore PolyBridge architecture">{polyStages.map((p,i)=><TabsTrigger key={p.title} value={String(i)}><span className="v4-meta">0{i+1}</span>{p.title}</TabsTrigger>)}</TabsList>{polyStages.map((p,i)=><TabsContent key={p.title} value={String(i)}><h3>{p.heading}</h3><p>{p.text}</p></TabsContent>)}</Tabs><div className="poly-research-footer"><span className="v4-meta">NEXT RESEARCH THREADS</span><p>AI-assisted translation <i>/</i> IDE tooling <i>/</i> WASM concepts <i>/</i> Extensible adapters</p></div></div>;
}
export function DataPipeline(){return <div className="v4-data-pipeline" aria-label="ML research workflow: inspect data, frame a question, define a contract, evaluate"><span className="v4-meta">RESEARCH BEFORE THE MODEL</span><svg viewBox="0 0 620 155" aria-hidden="true">{Array.from({length:25},(_,i)=><path key={i} d={`M0 ${10+i*5.5}C150 ${10+i*5.5} 110 80 210 80S360 ${20+(i%5)*27} 430 ${20+(i%5)*27}S520 80 620 80`} opacity={.14+(i%4)*.06}/>)}<circle cx="210" cy="80" r="5"/><circle cx="620" cy="80" r="5"/></svg><div className="data-stage-labels v4-meta"><span>DATA</span><span>QUESTION</span><span>CONTRACT</span><span>EVALUATE</span></div></div>;}
